import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Nav from '@/components/Nav'
import Pie from '@/components/Pie'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Modulares Grifer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/modulares-logo.png" type="image/x-icon" />
      <body className={inter.className}>
        <Nav/>
        {children}
        <Pie/>
      </body>
    </html>
  )
}
